import pygame

pygame.init()

WIN_WIDTH, WIN_HEIGHT = 1280, 720

FPS = 60

#---RULE SETTINGS---
WINNING_SCORE = 5


#---PLAYERS SETTINGS---
NUM_OF_PLAYERS = None
PLAYER_WIDTH = 20
PLAYER_HEIGHT = 100

#---BALL SETTINGS---
BALL_RADIUS = 10
BALL_SPEED = 5

#---POWERUPS SETTINGS---
POWERUP_RADIUS = 15
POWERUP_SPAWN_TIME = 5
SPAWN_MIN_X = WIN_WIDTH // 4
SPAWN_MAX_X = WIN_WIDTH - WIN_WIDTH // 4
SPAWN_MIN_Y = WIN_HEIGHT // 4
SPAWN_MAX_Y = WIN_HEIGHT - WIN_HEIGHT // 4
POWERUP_REVERSE = "Reverse"
POWERUP_WALL = "Wall"
POWERUP_WALL_WIDTH = 10
POWERUP_CURSE = "Curse"
POWERUP_WALL_DURATION = 0.5
POWERUP_CURSE_SIZE = PLAYER_HEIGHT * 0.3
POWERUP_CURSE_DURATION = 5
POWERUP_SPAWN_INTERVAL = 5

SCORE_FONT = pygame.font.SysFont("comicsans", 50)